apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: edu
  labels:
    app: pod-test
spec:
  containers:
  - name: nginx
    image: nginx:1.22.1
    env:
    - name: TEST_ENV
      value: "its-env"
    command: ["/bin/sh"]
    args: ["-c", "echo $TEST_ENV && sleep 1d"]
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "echo 'hello world' && sleep 1d"]
