apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: edu
  labels:
    app: pod-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    command: ["/bin/sh"]
    args: ["-c", "echo 'this line is edit from k8s command & args'> /usr/share/nginx/html/index.html && sleep 1d"]
    ports:
    - containerPort: 80
