apiVersion: v1
kind: Service
metadata:
  name: replicaset-service
  namespace: edu
spec:
  selector:
    tier: replicaset
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  externalIPs:
  - 192.168.0.6
