apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-pod
  labels:
    app: initcontainer-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: nginx-http-port
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: initcontainer-volume
  initContainers:
  - name: initcontainer
    image: busybox
    command: ['sh', '-c', "echo 'initContainer create or edit this html file'>/data/index.html"]
    volumeMounts:
    - mountPath: /data
      name: initcontainer-volume
  volumes:
  - name: initcontainer-volume
    hostPath:
      path: /tmp/initcontainer-hostpath
      type: DirectoryOrCreate
